# .github/workflows/netlify.yml
name: Build and Deploy to Netlify
on:
  push:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      #  Install dependencies
      - run: npm ci

      #  Build and Test
      - run: npm run build --if-present
      - run: npm run test

      # ( Build to ./dist or other directory... )

      - name: Deploy to Netlify
        uses: jsmrcaga/action-netlify-deploy@master
        with:
          build_directory: 'dist'
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
           NETLIFY_DEPLOY_MESSAGE: "Prod deploy v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true
        timeout-minutes: 1